[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "alembic>=1.15.1",
    "fastapi[all]>=0.115.11",
    "sqlmodel>=0.0.24",
]

[dependency-groups]
dev = [
    "ruff>=0.9.10",
]
